#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"

query AdminQuery {
  currentUser {
    ...UserEntry
    house {
      ...HouseEntry
    }
    isAdmin
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
}
