#import "fragments/EventEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/UserEntry.gql"

query EventsQuery($houseId: ID, $sortBy: EventSortEnum,) {
  currentUser {
    ...UserEntry
    isAdmin
  }
  events(houseId: $houseId, sortBy: $sortBy) {
    ...EventEntry
    signupCount
    house {
      ...HouseEntry
    }
    organization {
      name
    }
  }
}
