#import "fragments/EventEntry.gql"
#import "fragments/EventTypeEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/OrganizationEntry.gql"
#import "fragments/UserEntry.gql"

query EventQuery($id: ID!) {
  event(id: $id) {
    ...EventEntry
    house {
      ...HouseEntry
    }
    eventType {
      ...EventTypeEntry
    }
    organization {
      ...OrganizationEntry
    }
    users {
      ...UserEntry
    }
    tags {
      id
      name
    }
  }
  eventTypes {
    ...EventTypeEntry
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
  organizations {
    ...OrganizationEntry
  }
  tags {
    id
    name
  }
}
