#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"

query ReportingQuery($after: Int, $before: Int, $houseId: ID) {
  currentUser {
    ...UserEntry
    house {
      ...HouseEntry
    }
    isAdmin
  }
  users(houseId: $houseId) {
    ...UserEntry
    hours(after: $after, before: $before)
    house {
      ...HouseEntry
    }
  }
}
