#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"

query LeaderboardQuery($count: Int, $sortBy: UserSortEnum, $houseId: ID, $after: Int, $before: Int) {
  volunteers(count: $count, sortBy: $sortBy, houseId: $houseId, after: $after, before: $before) {
    ...UserEntry
    hours(after: $after, before: $before)
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
}
