#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/UserPreferenceEntry.gql"

query AppQuery {
  currentUser {
    ...UserEntry
    lastSignInAt
    isAdmin
    house {
      ...HouseEntry
    }
    preference {
      ...UserPreferenceEntry
    }
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
}
