#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/OrganizationEntry.gql"
#import "fragments/EventTypeEntry.gql"
#import "fragments/IndividualEventEntry.gql"

query PendingIndividualEventsQuery {
  currentUser {
    ...UserEntry
    house {
      ...HouseEntry
    }
    isAdmin
  }
  pendingIndividualEvents {
    ...IndividualEventEntry
    user {
      ...UserEntry
    }
    organization {
      ...OrganizationEntry
    }
    eventType {
      ...EventTypeEntry
    }
  }
}
