#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"

query UserQuery($id: ID!) {
  user(id: $id) {
    ...UserEntry
    house {
      ...HouseEntry
    }
    timezone
    isAdmin
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
}
