#import "fragments/UserEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/OrganizationEntry.gql"

query MyEventsQuery {
  currentUser {
    ...UserEntry
    individualEvents {
      id
      status
      duration
      date
      description
      organization {
        ...OrganizationEntry
      }
      eventType {
        id
        title
      }
      house {
        ...HouseEntry
      }
      tags {
        id
        name
      }
    }
    signups {
      event {
        title
        duration
        startsAt
        description
        organization {
          name
        }
        eventType {
          title
        }
        location
      }
    }
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
  eventTypes {
    id
    title
  }
  organizations {
    ...OrganizationEntry
  }
  tags {
    id
    name
  }
}
