#import "fragments/EventEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/UserEntry.gql"

query FetchMoreQuery($after: Int, $before: Int) {
  events(after: $after, before: $before) {
    ...EventEntry
    signupCount
    house {
      ...HouseEntry
    }
    users {
      ...UserEntry
    }
  }
}
