#import "fragments/UserEntry.gql"
#import "fragments/EventEntry.gql"
#import "fragments/HouseEntry.gql"
#import "fragments/UserEntry.gql"

query EventsQuery($after: Int, $before: Int, $houseId: ID) {
  currentUser {
    ...UserEntry
    isAdmin
    house {
      ...HouseEntry
    }
  }
  events(after: $after, before: $before, houseId: $houseId) {
    ...EventEntry
    signupCount
    house {
      ...HouseEntry
    }
    users {
      ...UserEntry
    }
  }
  houses(sortBy: NAME_ASC) {
    ...HouseEntry
  }
}
